export const MODELS = {
  // --- OpenAI chat (vision input supported) ---
  "gpt-4o": {
    provider: "openai",
    kind: "chat",
    caps: { visionInput: true, imageGen: false, audioIn: true, audioOut: false },
    context: 128000,
    price: { in: 5.0, out: 15.0 },
    display: { name: "GPT-4o", group: "OpenAI" },
    temperatureSupported: true,
  },
  "gpt-4o-mini": {
    provider: "openai",
    kind: "chat",
    caps: { visionInput: false, imageGen: false, audioIn: false, audioOut: false },
    context: 128000,
    price: { in: 0.15, out: 0.60 },
    display: { name: "GPT-4o mini", group: "OpenAI" },
    temperatureSupported: true,
  },
  "gpt-4-turbo": {
    provider: "openai",
    kind: "chat",
    caps: { visionInput: true, imageGen: false, audioIn: false, audioOut: false },
    context: 128000,
    price: { in: 2.5, out: 10.0 },
    display: { name: "GPT-4 Turbo", group: "OpenAI" },
    temperatureSupported: true,
  },
  "gpt-3.5-turbo": {
    provider: "openai",
    kind: "chat",
    caps: { visionInput: false, imageGen: false, audioIn: false, audioOut: false },
    context: 16384,
    price: { in: 0.5, out: 1.5 },
    display: { name: "GPT-3.5 Turbo", group: "OpenAI" },
    temperatureSupported: true,
  },

  // --- Runware Image Models ---
  "runware-flux-dev": {
    provider: "runware",
    kind: "image",
    caps: { visionInput: false, imageGen: true, audioIn: false, audioOut: false },
    context: 0,
    price: { in: 0, out: 0.0038 },
    display: { name: "FLUX.1 dev", group: "Runware" },
    temperatureSupported: false,
  },
  "runware-flux-schnell": {
    provider: "runware",
    kind: "image",
    caps: { visionInput: false, imageGen: true, audioIn: false, audioOut: false },
    context: 0,
    price: { in: 0, out: 0.0013 },
    display: { name: "FLUX.1 schnell", group: "Runware" },
    temperatureSupported: false,
  },
  "runware-flux-canny": {
    provider: "runware",
    kind: "image",
    caps: { visionInput: false, imageGen: true, audioIn: false, audioOut: false },
    context: 0,
    price: { in: 0, out: 0.0038 },
    display: { name: "FLUX.1 Canny", group: "Runware" },
    temperatureSupported: false,
  },
  "runware-sdxl-civitai": {
    provider: "runware",
    kind: "image",
    caps: { visionInput: false, imageGen: true, audioIn: false, audioOut: false },
    context: 0,
    price: { in: 0, out: 0.0025 },
    display: { name: "SDXL (Civitai)", group: "Runware" },
    temperatureSupported: false,
  },

  // --- Anthropic ---
  "claude-3.7-sonnet": {
    provider: "anthropic",
    kind: "chat",
    caps: { visionInput: true, imageGen: false, audioIn: false, audioOut: false },
    context: 200000,
    price: { in: 3.0, out: 15.0 },
    display: { name: "Claude 3.7 Sonnet", group: "Anthropic" },
    temperatureSupported: true,
  },
  "claude-3-haiku": {
    provider: "anthropic",
    kind: "chat",
    caps: { visionInput: false, imageGen: false, audioIn: false, audioOut: false },
    context: 200000,
    price: { in: 0.25, out: 1.25 },
    display: { name: "Claude 3 Haiku", group: "Anthropic" },
    temperatureSupported: true,
  },

  // --- Google ---
  "gemini-2.5-pro": {
    provider: "google",
    kind: "chat",
    caps: { visionInput: true, imageGen: false, audioIn: true, audioOut: false },
    context: 1000000,
    price: { in: 0.5, out: 1.5 },
    display: { name: "Gemini 2.5 Pro", group: "Google" },
    temperatureSupported: true,
  },
};